version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies
      - apt-get update -y && apt-get install -y zip
  build:
    commands:
      - echo Building the HTML project
      - zip -r build.zip *
artifacts:
  files:
    - build.zip

